import { collection, addDoc } from "firebase/firestore";
import { db } from "./firebaseConfig.js";

/**
 * Adds a new photo document to the "photos" collection in Firestore.
 * This method automatically generates a unique ID for the new document.
 *
 * @param {object} newPhoto - The photo metadata to be stored.
 * @returns {Promise<string>} - A promise that resolves with the unique document ID on success.
 * @throws {Error} - Throws a user-friendly error message on failure.
 */
const addPhoto = async (newPhoto) => {
  // Get a reference to the 'photos' collection
  const photosCollectionRef = collection(db, "photos");

  try {
    // Call addDoc to automatically generate a unique ID and save the document
    const docRef = await addDoc(photosCollectionRef, newPhoto);

    // Console log for developer feedback
    console.log(
      `[Firestore] New document successfully added with ID: ${docRef.id}`
    );

    // Return the unique ID generated by Firestore
    return docRef.id;
  } catch (error) {
    // Console log for developer debugging
    console.error("[Firestore Error] Failed to add document:", error);

    // 1. Error Handling for the Frontend (User-facing message in Spanish)
    // Throw an error that the calling component can catch and display to the user.
    throw new Error(
      "🚨 Error al guardar la foto. Por favor, inténtalo de nuevo."
    );
  }
};

export { addPhoto };
