export const unsplash = {
  total: 6455,
  total_pages: 646,
  results: [
    {
      id: "3purECWQ47I",
      slug: "a-large-building-with-a-fountain-in-front-of-it-3purECWQ47I",
      alternative_slugs: {
        en: "a-large-building-with-a-fountain-in-front-of-it-3purECWQ47I",
        es: "un-gran-edificio-con-una-fuente-frente-a-el-3purECWQ47I",
        ja: "前に噴水がある大きな建物-3purECWQ47I",
        fr: "un-grand-batiment-avec-une-fontaine-devant-lui-3purECWQ47I",
        it: "un-grande-edificio-con-una-fontana-di-fronte-ad-esso-3purECWQ47I",
        ko: "앞에-분수대가-있는-큰-건물-3purECWQ47I",
        de: "ein-grosses-gebaude-mit-einem-brunnen-davor-3purECWQ47I",
        pt: "um-grande-edificio-com-uma-fonte-a-sua-frente-3purECWQ47I",
        id: "sebuah-bangunan-besar-dengan-air-mancur-di-depannya-3purECWQ47I",
      },
      created_at: "2023-07-03T17:32:57Z",
      updated_at: "2025-10-16T12:42:28Z",
      promoted_at: null,
      width: 5971,
      height: 3955,
      color: "#d9d9f3",
      blur_hash: "LoLNMh$LIUjs%%NaWAn%tmofNHWW",
      description: null,
      alt_description: "a large building with a fountain in front of it",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1688404808661-92f72f2ea258?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1688404808661-92f72f2ea258?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1688404808661-92f72f2ea258?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1688404808661-92f72f2ea258?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1688404808661-92f72f2ea258?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1688404808661-92f72f2ea258",
      },
      links: {
        self: "https://api.unsplash.com/photos/a-large-building-with-a-fountain-in-front-of-it-3purECWQ47I",
        html: "https://unsplash.com/photos/a-large-building-with-a-fountain-in-front-of-it-3purECWQ47I",
        download:
          "https://unsplash.com/photos/3purECWQ47I/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/3purECWQ47I/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 23,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {},
      asset_type: "photo",
      user: {
        id: "414JRynq6xo",
        updated_at: "2025-10-01T13:48:40Z",
        username: "taisiat",
        name: "Taisia Karaseva",
        first_name: "Taisia",
        last_name: "Karaseva",
        twitter_username: null,
        portfolio_url: "https://www.taisiat.com/",
        bio: "Software engineer, problem solver, builder with a lifelong passion to capture the moment with a camera.",
        location: "San Francisco",
        links: {
          self: "https://api.unsplash.com/users/taisiat",
          html: "https://unsplash.com/@taisiat",
          photos: "https://api.unsplash.com/users/taisiat/photos",
          likes: "https://api.unsplash.com/users/taisiat/likes",
          portfolio: "https://api.unsplash.com/users/taisiat/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1685743275285-8a7836810e78image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1685743275285-8a7836810e78image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1685743275285-8a7836810e78image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "tk_dreams_of_tea",
        total_collections: 0,
        total_likes: 1,
        total_photos: 235,
        total_promoted_photos: 0,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: true,
        social: {
          instagram_username: "tk_dreams_of_tea",
          portfolio_url: "https://www.taisiat.com/",
          twitter_username: null,
          paypal_email: null,
        },
      },
    },
    {
      id: "a96wj8idE_I",
      slug: "a-large-building-with-a-flag-on-top-a96wj8idE_I",
      alternative_slugs: {
        en: "a-large-building-with-a-flag-on-top-a96wj8idE_I",
        es: "un-gran-edificio-con-una-bandera-en-la-parte-superior-a96wj8idE_I",
        ja: "旗が上にある大きな建物-a96wj8idE_I",
        fr: "un-grand-batiment-avec-un-drapeau-sur-le-dessus-a96wj8idE_I",
        it: "un-grande-edificio-con-una-bandiera-in-cima-a96wj8idE_I",
        ko: "위에-깃발이있는-큰-건물-a96wj8idE_I",
        de: "ein-grosses-gebaude-mit-einer-flagge-oben-a96wj8idE_I",
        pt: "um-grande-edificio-com-uma-bandeira-no-topo-a96wj8idE_I",
        id: "sebuah-bangunan-besar-dengan-bendera-di-atasnya-a96wj8idE_I",
      },
      created_at: "2022-08-25T15:48:19Z",
      updated_at: "2025-10-16T12:27:08Z",
      promoted_at: "2022-08-25T17:00:01Z",
      width: 3816,
      height: 5717,
      color: "#59a6d9",
      blur_hash: "LcI5Pv-4xt%K1,w[xBoII]Nei^oJ",
      description: null,
      alt_description: "a large building with a flag on top",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1661442196003-f2f6eb54bd94?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1661442196003-f2f6eb54bd94?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1661442196003-f2f6eb54bd94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1661442196003-f2f6eb54bd94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1661442196003-f2f6eb54bd94?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1661442196003-f2f6eb54bd94",
      },
      links: {
        self: "https://api.unsplash.com/photos/a-large-building-with-a-flag-on-top-a96wj8idE_I",
        html: "https://unsplash.com/photos/a-large-building-with-a-flag-on-top-a96wj8idE_I",
        download:
          "https://unsplash.com/photos/a96wj8idE_I/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/a96wj8idE_I/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwyfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 117,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {
        "architecture-interior": {
          status: "rejected",
        },
        nature: {
          status: "approved",
          approved_on: "2022-09-02T14:04:36Z",
        },
      },
      asset_type: "photo",
      user: {
        id: "DecmfIoTRIM",
        updated_at: "2025-07-08T20:56:38Z",
        username: "shotsbytania",
        name: "Tânia Mousinho",
        first_name: "Tânia",
        last_name: "Mousinho",
        twitter_username: "taniaxsofia",
        portfolio_url: "http://www.shotsbytania.com",
        bio: "London-based photographer. Thank you for supporting my work! Please tag me in any images used.\r\n TikTok: @shotsbytania",
        location: "London",
        links: {
          self: "https://api.unsplash.com/users/shotsbytania",
          html: "https://unsplash.com/@shotsbytania",
          photos: "https://api.unsplash.com/users/shotsbytania/photos",
          likes: "https://api.unsplash.com/users/shotsbytania/likes",
          portfolio: "https://api.unsplash.com/users/shotsbytania/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "shotsbytania",
        total_collections: 6,
        total_likes: 7892,
        total_photos: 275,
        total_promoted_photos: 25,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: true,
        social: {
          instagram_username: "shotsbytania",
          portfolio_url: "http://www.shotsbytania.com",
          twitter_username: "taniaxsofia",
          paypal_email: null,
        },
      },
    },
    {
      id: "62QRdDoe44M",
      slug: "brown-concrete-building-during-daytime-photo-62QRdDoe44M",
      alternative_slugs: {
        en: "brown-concrete-building-during-daytime-photo-62QRdDoe44M",
        es: "edificio-de-hormigon-marron-durante-el-dia-foto-62QRdDoe44M",
        ja: "昼間の茶色のコンクリートの建物-写真-62QRdDoe44M",
        fr: "batiment-en-beton-brun-pendant-la-photo-de-jour-62QRdDoe44M",
        it: "edificio-in-cemento-marrone-durante-la-foto-diurna-62QRdDoe44M",
        ko: "갈색-콘크리트-건물-동안-낮-사진-62QRdDoe44M",
        de: "braunes-betongebaude-wahrend-des-tages-foto-62QRdDoe44M",
        pt: "edificio-de-concreto-marrom-durante-a-foto-diurna-62QRdDoe44M",
        id: "bangunan-beton-coklat-selama-foto-siang-hari-62QRdDoe44M",
      },
      created_at: "2017-11-05T00:17:03Z",
      updated_at: "2025-10-16T15:00:56Z",
      promoted_at: null,
      width: 5094,
      height: 3396,
      color: "#c0d9d9",
      blur_hash: "LqLNSsWBjts-?^jZWVWqOaofWBay",
      description: "Seville Sunset",
      alt_description: "brown concrete building during daytime photo",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1509840841025-9088ba78a826?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1509840841025-9088ba78a826?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1509840841025-9088ba78a826?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1509840841025-9088ba78a826?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1509840841025-9088ba78a826?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1509840841025-9088ba78a826",
      },
      links: {
        self: "https://api.unsplash.com/photos/brown-concrete-building-during-daytime-photo-62QRdDoe44M",
        html: "https://unsplash.com/photos/brown-concrete-building-during-daytime-photo-62QRdDoe44M",
        download:
          "https://unsplash.com/photos/62QRdDoe44M/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/62QRdDoe44M/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwzfHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 360,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {
        nature: {
          status: "approved",
          approved_on: "2021-08-16T11:25:53Z",
        },
      },
      asset_type: "photo",
      user: {
        id: "rBvON6YD9Bk",
        updated_at: "2025-10-16T17:55:02Z",
        username: "rickpsd",
        name: "Henrique Ferreira",
        first_name: "Henrique",
        last_name: "Ferreira",
        twitter_username: null,
        portfolio_url: null,
        bio: "Landscapes, sunsets, my dog.",
        location: "Zurich, Switzerland",
        links: {
          self: "https://api.unsplash.com/users/rickpsd",
          html: "https://unsplash.com/@rickpsd",
          photos: "https://api.unsplash.com/users/rickpsd/photos",
          likes: "https://api.unsplash.com/users/rickpsd/likes",
          portfolio: "https://api.unsplash.com/users/rickpsd/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1473327357105-af064209789c?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1473327357105-af064209789c?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1473327357105-af064209789c?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "rick_final.gif",
        total_collections: 2,
        total_likes: 163,
        total_photos: 154,
        total_promoted_photos: 19,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: true,
        social: {
          instagram_username: "rick_final.gif",
          portfolio_url: null,
          twitter_username: null,
          paypal_email: null,
        },
      },
    },
    {
      id: "PWrNP4bQHB4",
      slug: "brown-concrete-structure-PWrNP4bQHB4",
      alternative_slugs: {
        en: "brown-concrete-structure-PWrNP4bQHB4",
        es: "estructura-de-hormigon-marron-PWrNP4bQHB4",
        ja: "茶色のコンクリート構造-PWrNP4bQHB4",
        fr: "structure-en-beton-brun-PWrNP4bQHB4",
        it: "struttura-in-calcestruzzo-marrone-PWrNP4bQHB4",
        ko: "갈색-콘크리트-구조물-PWrNP4bQHB4",
        de: "braune-betonstruktur-PWrNP4bQHB4",
        pt: "estrutura-de-concreto-marrom-PWrNP4bQHB4",
        id: "struktur-beton-coklat-PWrNP4bQHB4",
      },
      created_at: "2019-06-03T12:21:51Z",
      updated_at: "2025-10-16T18:00:46Z",
      promoted_at: null,
      width: 6000,
      height: 4000,
      color: "#408ca6",
      blur_hash: "LbG]K=$zRQRj14NGoLt7S%o}ayWA",
      description: null,
      alt_description: "brown concrete structure",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1559564477-6e8582270002?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1559564477-6e8582270002?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1559564477-6e8582270002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1559564477-6e8582270002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1559564477-6e8582270002?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1559564477-6e8582270002",
      },
      links: {
        self: "https://api.unsplash.com/photos/brown-concrete-structure-PWrNP4bQHB4",
        html: "https://unsplash.com/photos/brown-concrete-structure-PWrNP4bQHB4",
        download:
          "https://unsplash.com/photos/PWrNP4bQHB4/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/PWrNP4bQHB4/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw0fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 127,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {},
      asset_type: "photo",
      user: {
        id: "hwbvHRbN9jY",
        updated_at: "2024-10-10T23:20:14Z",
        username: "joanoger",
        name: "Joan Oger",
        first_name: "Joan",
        last_name: "Oger",
        twitter_username: "Ogerjoan",
        portfolio_url: "https://www.instagram.com/joanoger/",
        bio: null,
        location: "18, Rue de la Haisse",
        links: {
          self: "https://api.unsplash.com/users/joanoger",
          html: "https://unsplash.com/@joanoger",
          photos: "https://api.unsplash.com/users/joanoger/photos",
          likes: "https://api.unsplash.com/users/joanoger/likes",
          portfolio: "https://api.unsplash.com/users/joanoger/portfolio",
          following: "https://api.unsplash.com/users/joanoger/following",
          followers: "https://api.unsplash.com/users/joanoger/followers",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1559822626135-69008023ec86?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1559822626135-69008023ec86?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1559822626135-69008023ec86?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "joanoger",
        total_collections: 0,
        total_likes: 237,
        total_photos: 58,
        total_promoted_photos: 7,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "joanoger",
          portfolio_url: "https://www.instagram.com/joanoger/",
          twitter_username: "Ogerjoan",
          paypal_email: null,
        },
      },
    },
    {
      id: "zsgZDg_OwLk",
      slug: "a-view-of-a-large-building-with-a-bridge-in-front-of-it-zsgZDg_OwLk",
      alternative_slugs: {
        en: "a-view-of-a-large-building-with-a-bridge-in-front-of-it-zsgZDg_OwLk",
        es: "una-vista-de-un-gran-edificio-con-un-puente-frente-a-el-zsgZDg_OwLk",
        ja: "大きな建物とその前に橋がある景色-zsgZDg_OwLk",
        fr: "une-vue-dun-grand-batiment-avec-un-pont-devant-lui-zsgZDg_OwLk",
        it: "una-vista-di-un-grande-edificio-con-un-ponte-di-fronte-ad-esso-zsgZDg_OwLk",
        ko: "앞에-다리가-있는-큰-건물의-모습-zsgZDg_OwLk",
        de: "ein-blick-auf-ein-grosses-gebaude-mit-einer-brucke-davor-zsgZDg_OwLk",
        pt: "uma-vista-de-um-grande-edificio-com-uma-ponte-a-sua-frente-zsgZDg_OwLk",
        id: "pemandangan-bangunan-besar-dengan-jembatan-di-depannya-zsgZDg_OwLk",
      },
      created_at: "2019-06-01T10:48:23Z",
      updated_at: "2025-10-16T15:34:18Z",
      promoted_at: null,
      width: 2567,
      height: 3420,
      color: "#8cc0d9",
      blur_hash: "LNE{b6Y7H;#PGKOuQ+VXI[aes8oe",
      description: null,
      alt_description:
        "a view of a large building with a bridge in front of it",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1559386081-325882507af7?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1559386081-325882507af7?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1559386081-325882507af7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1559386081-325882507af7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1559386081-325882507af7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1559386081-325882507af7",
      },
      links: {
        self: "https://api.unsplash.com/photos/a-view-of-a-large-building-with-a-bridge-in-front-of-it-zsgZDg_OwLk",
        html: "https://unsplash.com/photos/a-view-of-a-large-building-with-a-bridge-in-front-of-it-zsgZDg_OwLk",
        download:
          "https://unsplash.com/photos/zsgZDg_OwLk/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/zsgZDg_OwLk/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw1fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 366,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {
        travel: {
          status: "approved",
          approved_on: "2024-07-02T09:20:35Z",
        },
      },
      asset_type: "photo",
      user: {
        id: "7nkWDl-2ZyE",
        updated_at: "2024-10-11T04:46:46Z",
        username: "iv2fi",
        name: "V2F",
        first_name: "V2F",
        last_name: null,
        twitter_username: "IV2FI",
        portfolio_url: "https://www.youtube.com/user/IV2FI",
        bio: "I love travelling and sharing my experiences",
        location: "France",
        links: {
          self: "https://api.unsplash.com/users/iv2fi",
          html: "https://unsplash.com/@iv2fi",
          photos: "https://api.unsplash.com/users/iv2fi/photos",
          likes: "https://api.unsplash.com/users/iv2fi/likes",
          portfolio: "https://api.unsplash.com/users/iv2fi/portfolio",
          following: "https://api.unsplash.com/users/iv2fi/following",
          followers: "https://api.unsplash.com/users/iv2fi/followers",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1578831201747-e675cb71bde5image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1578831201747-e675cb71bde5image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1578831201747-e675cb71bde5image?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "IV2FI",
        total_collections: 0,
        total_likes: 0,
        total_photos: 25,
        total_promoted_photos: 0,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "IV2FI",
          portfolio_url: "https://www.youtube.com/user/IV2FI",
          twitter_username: "IV2FI",
          paypal_email: null,
        },
      },
    },
    {
      id: "ZK_v7Uc7sqQ",
      slug: "people-around-brown-building-ZK_v7Uc7sqQ",
      alternative_slugs: {
        en: "people-around-brown-building-ZK_v7Uc7sqQ",
        es: "gente-alrededor-del-edificio-brown-ZK_v7Uc7sqQ",
        ja: "ブラウンビル周辺の人々-ZK_v7Uc7sqQ",
        fr: "gens-autour-de-limmeuble-brun-ZK_v7Uc7sqQ",
        it: "persone-intorno-a-brown-building-ZK_v7Uc7sqQ",
        ko: "브라운-빌딩-주변-사람들-ZK_v7Uc7sqQ",
        de: "menschen-rund-um-das-brown-building-ZK_v7Uc7sqQ",
        pt: "pessoas-ao-redor-de-brown-building-ZK_v7Uc7sqQ",
        id: "orang-orang-di-sekitar-gedung-coklat-ZK_v7Uc7sqQ",
      },
      created_at: "2019-06-19T17:17:20Z",
      updated_at: "2025-10-16T18:12:43Z",
      promoted_at: null,
      width: 5848,
      height: 3899,
      color: "#a6d9d9",
      blur_hash: "LQHoRQ%#%MX9?^tlsSo~KkI:Mdg3",
      description: null,
      alt_description: "people around brown building",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1560964598-dee5d2b9dd6b?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1560964598-dee5d2b9dd6b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1560964598-dee5d2b9dd6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1560964598-dee5d2b9dd6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1560964598-dee5d2b9dd6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1560964598-dee5d2b9dd6b",
      },
      links: {
        self: "https://api.unsplash.com/photos/people-around-brown-building-ZK_v7Uc7sqQ",
        html: "https://unsplash.com/photos/people-around-brown-building-ZK_v7Uc7sqQ",
        download:
          "https://unsplash.com/photos/ZK_v7Uc7sqQ/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/ZK_v7Uc7sqQ/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw2fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 101,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {},
      asset_type: "photo",
      user: {
        id: "hwbvHRbN9jY",
        updated_at: "2024-10-10T23:20:14Z",
        username: "joanoger",
        name: "Joan Oger",
        first_name: "Joan",
        last_name: "Oger",
        twitter_username: "Ogerjoan",
        portfolio_url: "https://www.instagram.com/joanoger/",
        bio: null,
        location: "18, Rue de la Haisse",
        links: {
          self: "https://api.unsplash.com/users/joanoger",
          html: "https://unsplash.com/@joanoger",
          photos: "https://api.unsplash.com/users/joanoger/photos",
          likes: "https://api.unsplash.com/users/joanoger/likes",
          portfolio: "https://api.unsplash.com/users/joanoger/portfolio",
          following: "https://api.unsplash.com/users/joanoger/following",
          followers: "https://api.unsplash.com/users/joanoger/followers",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1559822626135-69008023ec86?ixlib=rb-4.0.3&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1559822626135-69008023ec86?ixlib=rb-4.0.3&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1559822626135-69008023ec86?ixlib=rb-4.0.3&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "joanoger",
        total_collections: 0,
        total_likes: 237,
        total_photos: 58,
        total_promoted_photos: 7,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "joanoger",
          portfolio_url: "https://www.instagram.com/joanoger/",
          twitter_username: "Ogerjoan",
          paypal_email: null,
        },
      },
    },
    {
      id: "dMi3pqiqhsw",
      slug: "a-large-brick-building-with-pillars-dMi3pqiqhsw",
      alternative_slugs: {
        en: "a-large-brick-building-with-pillars-dMi3pqiqhsw",
        es: "un-gran-edificio-de-ladrillo-con-pilares-dMi3pqiqhsw",
        ja: "柱のある大きなレンガ造りの建物-dMi3pqiqhsw",
        fr: "un-grand-batiment-en-briques-avec-des-piliers-dMi3pqiqhsw",
        it: "un-grande-edificio-in-mattoni-con-pilastri-dMi3pqiqhsw",
        ko: "기둥이있는-큰-벽돌-건물-dMi3pqiqhsw",
        de: "ein-grosses-backsteingebaude-mit-saulen-dMi3pqiqhsw",
        pt: "um-grande-edificio-de-tijolos-com-pilares-dMi3pqiqhsw",
        id: "bangunan-bata-besar-dengan-pilar-dMi3pqiqhsw",
      },
      created_at: "2022-08-25T15:48:19Z",
      updated_at: "2025-10-16T12:44:26Z",
      promoted_at: null,
      width: 5131,
      height: 3406,
      color: "#260c0c",
      blur_hash: "LOF=RC?wJBxu9^x^xvNHDiR4fSo#",
      description: null,
      alt_description: "a large brick building with pillars",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1661442196029-ecc4a8e0a0b8?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1661442196029-ecc4a8e0a0b8?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1661442196029-ecc4a8e0a0b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1661442196029-ecc4a8e0a0b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1661442196029-ecc4a8e0a0b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1661442196029-ecc4a8e0a0b8",
      },
      links: {
        self: "https://api.unsplash.com/photos/a-large-brick-building-with-pillars-dMi3pqiqhsw",
        html: "https://unsplash.com/photos/a-large-brick-building-with-pillars-dMi3pqiqhsw",
        download:
          "https://unsplash.com/photos/dMi3pqiqhsw/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/dMi3pqiqhsw/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw3fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 20,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {
        "architecture-interior": {
          status: "rejected",
        },
        nature: {
          status: "rejected",
        },
      },
      asset_type: "photo",
      user: {
        id: "DecmfIoTRIM",
        updated_at: "2025-07-08T20:56:38Z",
        username: "shotsbytania",
        name: "Tânia Mousinho",
        first_name: "Tânia",
        last_name: "Mousinho",
        twitter_username: "taniaxsofia",
        portfolio_url: "http://www.shotsbytania.com",
        bio: "London-based photographer. Thank you for supporting my work! Please tag me in any images used.\r\n TikTok: @shotsbytania",
        location: "London",
        links: {
          self: "https://api.unsplash.com/users/shotsbytania",
          html: "https://unsplash.com/@shotsbytania",
          photos: "https://api.unsplash.com/users/shotsbytania/photos",
          likes: "https://api.unsplash.com/users/shotsbytania/likes",
          portfolio: "https://api.unsplash.com/users/shotsbytania/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "shotsbytania",
        total_collections: 6,
        total_likes: 7892,
        total_photos: 275,
        total_promoted_photos: 25,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: true,
        social: {
          instagram_username: "shotsbytania",
          portfolio_url: "http://www.shotsbytania.com",
          twitter_username: "taniaxsofia",
          paypal_email: null,
        },
      },
    },
    {
      id: "UeSZNsV7GZE",
      slug: "brown-concrete-building-UeSZNsV7GZE",
      alternative_slugs: {
        en: "brown-concrete-building-UeSZNsV7GZE",
        es: "edificio-de-hormigon-marron-UeSZNsV7GZE",
        ja: "茶色のコンクリートの建物-UeSZNsV7GZE",
        fr: "batiment-en-beton-brun-UeSZNsV7GZE",
        it: "edificio-in-cemento-marrone-UeSZNsV7GZE",
        ko: "갈색-콘크리트-건물-UeSZNsV7GZE",
        de: "gebaude-aus-braunem-beton-UeSZNsV7GZE",
        pt: "edificio-de-concreto-marrom-UeSZNsV7GZE",
        id: "bangunan-beton-coklat-UeSZNsV7GZE",
      },
      created_at: "2018-11-13T13:18:33Z",
      updated_at: "2025-10-16T16:17:10Z",
      promoted_at: null,
      width: 6000,
      height: 4000,
      color: "#f3c08c",
      blur_hash: "LgIh21oyI[a#ThR-xtju18R+WBWB",
      description: "Placa Esapana, Seville",
      alt_description: "brown concrete building",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1542115049-3af45a7e0ff4?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1542115049-3af45a7e0ff4?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1542115049-3af45a7e0ff4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1542115049-3af45a7e0ff4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1542115049-3af45a7e0ff4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1542115049-3af45a7e0ff4",
      },
      links: {
        self: "https://api.unsplash.com/photos/brown-concrete-building-UeSZNsV7GZE",
        html: "https://unsplash.com/photos/brown-concrete-building-UeSZNsV7GZE",
        download:
          "https://unsplash.com/photos/UeSZNsV7GZE/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/UeSZNsV7GZE/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw4fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 39,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {},
      asset_type: "photo",
      user: {
        id: "kArtsAql7wI",
        updated_at: "2025-09-20T15:48:35Z",
        username: "shaipal",
        name: "Shai Pal",
        first_name: "Shai",
        last_name: "Pal",
        twitter_username: "shai_pal",
        portfolio_url: "http://shaipal.com",
        bio: "Senior Product Designer @Google, traveler, photographer, cake enthusiast, father of 2 (cats)",
        location: "Tel Aviv",
        links: {
          self: "https://api.unsplash.com/users/shaipal",
          html: "https://unsplash.com/@shaipal",
          photos: "https://api.unsplash.com/users/shaipal/photos",
          likes: "https://api.unsplash.com/users/shaipal/likes",
          portfolio: "https://api.unsplash.com/users/shaipal/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-fb-1515513511-ed2a816b5369.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-fb-1515513511-ed2a816b5369.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-fb-1515513511-ed2a816b5369.jpg?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "shai.pal",
        total_collections: 0,
        total_likes: 14,
        total_photos: 550,
        total_promoted_photos: 12,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: false,
        social: {
          instagram_username: "shai.pal",
          portfolio_url: "http://shaipal.com",
          twitter_username: "shai_pal",
          paypal_email: null,
        },
      },
    },
    {
      id: "n4z9z2EJlvw",
      slug: "a-narrow-city-street-lined-with-tall-buildings-n4z9z2EJlvw",
      alternative_slugs: {
        en: "a-narrow-city-street-lined-with-tall-buildings-n4z9z2EJlvw",
        es: "una-estrecha-calle-de-la-ciudad-bordeada-de-edificios-altos-n4z9z2EJlvw",
        ja: "高層ビルが立ち並ぶ狭い街並み-n4z9z2EJlvw",
        fr: "une-rue-etroite-de-la-ville-bordee-de-grands-immeubles-n4z9z2EJlvw",
        it: "una-stretta-strada-della-citta-fiancheggiata-da-edifici-alti-n4z9z2EJlvw",
        ko: "고층-건물들이-늘어선-좁은-도시-거리-n4z9z2EJlvw",
        de: "eine-schmale-stadtstrasse-mit-hohen-gebauden-gesaumt-n4z9z2EJlvw",
        pt: "uma-rua-estreita-da-cidade-alinhada-com-edificios-altos-n4z9z2EJlvw",
        id: "jalan-kota-sempit-yang-dipenuhi-dengan-gedung-gedung-tinggi-n4z9z2EJlvw",
      },
      created_at: "2021-10-12T14:29:59Z",
      updated_at: "2025-10-16T17:11:50Z",
      promoted_at: null,
      width: 3957,
      height: 5936,
      color: "#594059",
      blur_hash: "LZHnX4S~jBIV?w%1s6NfK7xD$xkr",
      description: "Side streets of Sevilla… part dos",
      alt_description: "a narrow city street lined with tall buildings",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1634048703492-eeded62bb987?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1634048703492-eeded62bb987?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1634048703492-eeded62bb987?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1634048703492-eeded62bb987?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1634048703492-eeded62bb987?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1634048703492-eeded62bb987",
      },
      links: {
        self: "https://api.unsplash.com/photos/a-narrow-city-street-lined-with-tall-buildings-n4z9z2EJlvw",
        html: "https://unsplash.com/photos/a-narrow-city-street-lined-with-tall-buildings-n4z9z2EJlvw",
        download:
          "https://unsplash.com/photos/n4z9z2EJlvw/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
        download_location:
          "https://api.unsplash.com/photos/n4z9z2EJlvw/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHw5fHxzZXZpbGxlfGVufDB8fHx8MTc2MDY0MDA3NXww",
      },
      likes: 203,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {
        "architecture-interior": {
          status: "rejected",
        },
        travel: {
          status: "rejected",
        },
        "street-photography": {
          status: "approved",
          approved_on: "2021-10-28T14:56:32Z",
        },
      },
      asset_type: "photo",
      user: {
        id: "8HbRRiXyo7E",
        updated_at: "2025-10-15T01:20:03Z",
        username: "tompodmore86",
        name: "Tom Podmore",
        first_name: "Tom",
        last_name: "Podmore",
        twitter_username: "Tompodmore86",
        portfolio_url: null,
        bio: "Nikon.",
        location: "Nottingham",
        links: {
          self: "https://api.unsplash.com/users/tompodmore86",
          html: "https://unsplash.com/@tompodmore86",
          photos: "https://api.unsplash.com/users/tompodmore86/photos",
          likes: "https://api.unsplash.com/users/tompodmore86/likes",
          portfolio: "https://api.unsplash.com/users/tompodmore86/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1605087494426-7310e2a7d616image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1605087494426-7310e2a7d616image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1605087494426-7310e2a7d616image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "tompodmore86",
        total_collections: 37,
        total_likes: 0,
        total_photos: 364,
        total_promoted_photos: 19,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: true,
        social: {
          instagram_username: "tompodmore86",
          portfolio_url: null,
          twitter_username: "Tompodmore86",
          paypal_email: null,
        },
      },
    },
    {
      id: "0QQzCZbBbuw",
      slug: "a-canal-with-a-boat-and-buildings-0QQzCZbBbuw",
      alternative_slugs: {
        en: "a-canal-with-a-boat-and-buildings-0QQzCZbBbuw",
        es: "un-canal-con-un-barco-y-edificios-0QQzCZbBbuw",
        ja: "ボートと建物のある運河-0QQzCZbBbuw",
        fr: "un-canal-avec-un-bateau-et-des-batiments-0QQzCZbBbuw",
        it: "un-canale-con-una-barca-e-edifici-0QQzCZbBbuw",
        ko: "보트와-건물이있는-운하-0QQzCZbBbuw",
        de: "ein-kanal-mit-einem-boot-und-gebauden-0QQzCZbBbuw",
        pt: "um-canal-com-um-barco-e-edificios-0QQzCZbBbuw",
        id: "kanal-dengan-perahu-dan-bangunan-0QQzCZbBbuw",
      },
      created_at: "2022-08-25T15:48:19Z",
      updated_at: "2025-10-16T18:02:41Z",
      promoted_at: null,
      width: 3864,
      height: 5788,
      color: "#c0a68c",
      blur_hash: "LKF?2[=|wIWC5]EMWUWBT#xbIofi",
      description: null,
      alt_description: "a canal with a boat and buildings",
      breadcrumbs: [],
      urls: {
        raw: "https://images.unsplash.com/photo-1661442197060-5fce68a9afc6?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA&ixlib=rb-4.1.0",
        full: "https://images.unsplash.com/photo-1661442197060-5fce68a9afc6?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA&ixlib=rb-4.1.0&q=85",
        regular:
          "https://images.unsplash.com/photo-1661442197060-5fce68a9afc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA&ixlib=rb-4.1.0&q=80&w=1080",
        small:
          "https://images.unsplash.com/photo-1661442197060-5fce68a9afc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA&ixlib=rb-4.1.0&q=80&w=400",
        thumb:
          "https://images.unsplash.com/photo-1661442197060-5fce68a9afc6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA&ixlib=rb-4.1.0&q=80&w=200",
        small_s3:
          "https://s3.us-west-2.amazonaws.com/images.unsplash.com/small/photo-1661442197060-5fce68a9afc6",
      },
      links: {
        self: "https://api.unsplash.com/photos/a-canal-with-a-boat-and-buildings-0QQzCZbBbuw",
        html: "https://unsplash.com/photos/a-canal-with-a-boat-and-buildings-0QQzCZbBbuw",
        download:
          "https://unsplash.com/photos/0QQzCZbBbuw/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA",
        download_location:
          "https://api.unsplash.com/photos/0QQzCZbBbuw/download?ixid=M3w4MTc1NTR8MHwxfHNlYXJjaHwxMHx8c2V2aWxsZXxlbnwwfHx8fDE3NjA2NDAwNzV8MA",
      },
      likes: 45,
      liked_by_user: false,
      bookmarked: false,
      current_user_collections: [],
      sponsorship: null,
      topic_submissions: {
        "architecture-interior": {
          status: "rejected",
        },
        nature: {
          status: "approved",
          approved_on: "2022-09-05T18:28:20Z",
        },
      },
      asset_type: "photo",
      user: {
        id: "DecmfIoTRIM",
        updated_at: "2025-07-08T20:56:38Z",
        username: "shotsbytania",
        name: "Tânia Mousinho",
        first_name: "Tânia",
        last_name: "Mousinho",
        twitter_username: "taniaxsofia",
        portfolio_url: "http://www.shotsbytania.com",
        bio: "London-based photographer. Thank you for supporting my work! Please tag me in any images used.\r\n TikTok: @shotsbytania",
        location: "London",
        links: {
          self: "https://api.unsplash.com/users/shotsbytania",
          html: "https://unsplash.com/@shotsbytania",
          photos: "https://api.unsplash.com/users/shotsbytania/photos",
          likes: "https://api.unsplash.com/users/shotsbytania/likes",
          portfolio: "https://api.unsplash.com/users/shotsbytania/portfolio",
        },
        profile_image: {
          small:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=32&h=32",
          medium:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=64&h=64",
          large:
            "https://images.unsplash.com/profile-1740401269029-5ce94e962199image?ixlib=rb-4.1.0&crop=faces&fit=crop&w=128&h=128",
        },
        instagram_username: "shotsbytania",
        total_collections: 6,
        total_likes: 7892,
        total_photos: 275,
        total_promoted_photos: 25,
        total_illustrations: 0,
        total_promoted_illustrations: 0,
        accepted_tos: true,
        for_hire: true,
        social: {
          instagram_username: "shotsbytania",
          portfolio_url: "http://www.shotsbytania.com",
          twitter_username: "taniaxsofia",
          paypal_email: null,
        },
      },
    },
  ],
};
